apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-hotstar
  labels:
    app: demo-hotstar
spec:
  replicas: 4
  selector:
    matchLabels:
      app: demo-hotstar
  template:
    metadata:
      labels:
        app: demo-hotstar
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: demo-hotstar
        image: 483216680875.dkr.ecr.us-east-1.amazonaws.com/hotstar:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 3000
